import { describe, expect, it, vi } from "vitest";
import { CivitaiSource, mapModelType, parseCivitaiUrl } from "../packages/model-sources/civitai/index.ts";

const fixture = { id: 1102, name: "SynthwavePunk", description: "<p>Bright &amp; cinematic.</p>", type: "Checkpoint", nsfw: false, creator: { username: "creator" }, modelVersions: [{ id: 1144, modelId: 1102, name: "V2", baseModel: "SD 1.5", createdAt: "2024-01-01T00:00:00Z", downloadUrl: "https://civitai.com/api/download/models/1144", files: [{ id: 196, name: "synth_v2.safetensors", sizeKB: 2, primary: true, metadata: { fp: "fp16", size: "pruned", format: "SafeTensor" }, hashes: { SHA256: "a".repeat(64) } }], images: [{ url: "https://image.civitai.com/example.jpeg", nsfw: false, width: 512, height: 768 }] }] };

describe("Civitai model source", () => {
  it.each([
    ["https://civitai.com/models/1102", { host: "civitai.com", modelId: 1102 }], ["https://www.civitai.com/models/1102/a-slug?modelVersionId=1144", { host: "civitai.com", modelId: 1102, versionId: 1144 }],
    ["https://civitai.red/models/1102", { host: "civitai.red", modelId: 1102 }], ["https://www.civitai.red/models/1102/a-slug", { host: "civitai.red", modelId: 1102 }],
  ])("parses supported model URL %s", (url, expected) => expect(parseCivitaiUrl(url)).toMatchObject(expected));
  it("parses provider direct download URLs", () => expect(parseCivitaiUrl("https://civitai.com/api/download/models/1144")).toMatchObject({ kind: "download", downloadId: 1144 }));
  it.each(["http://civitai.com/models/1", "https://civitai.com:444/models/1", "https://user:pass@civitai.com/models/1", "https://civitai.com.evil.test/models/1", "https://127.0.0.1/models/1", "https://civitai.com/models/nope", `https://civitai.com/models/1?${"x".repeat(2050)}`])("rejects unsafe URL %s", url => expect(() => parseCivitaiUrl(url)).toThrow());
  it("runtime-validates and normalizes model metadata", async () => { const request = vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(fixture), { status: 200 })); const model = await new CivitaiSource(request).resolve("https://civitai.com/models/1102?modelVersionId=1144", "automatic"); expect(model).toMatchObject({ provider: "civitai", providerHost: "civitai.com", modelId: 1102, type: "checkpoint", requestedVersionId: 1144, versions: [{ files: [{ fileId: 196, sizeBytes: 2048, primary: true }] }] }); expect(request.mock.calls[0]?.[1]?.headers).not.toEqual(expect.objectContaining({ Authorization: expect.anything() })); });
  it("uses one host strategy and never sends a credential to another host", async () => { const request = vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(fixture), { status: 200 })); await new CivitaiSource(request).resolve("https://civitai.red/models/1102", "civitai.red", "secret-value"); expect(request.mock.calls[0]?.[0]).toBe("https://civitai.red/api/v1/models/1102"); expect(request.mock.calls[0]?.[1]).toMatchObject({ redirect: "error", headers: expect.objectContaining({ Authorization: "Bearer secret-value" }) }); });
  it("maps supported Civitai types and rejects invalid responses", async () => { expect(mapModelType("TextualInversion")).toBe("embedding"); expect(mapModelType("LORA")).toBe("lora"); const source = new CivitaiSource(vi.fn<typeof fetch>().mockResolvedValue(new Response("{}", { status: 200 }))); await expect(source.resolve("https://civitai.com/models/1", "automatic")).rejects.toMatchObject({ detail: { code: "CIVITAI_RESPONSE_INVALID" } }); });
});
