import { createHash } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"; import { tmpdir } from "node:os"; import { resolve } from "node:path";
import { DownloadManager } from "../packages/download-manager/index.ts";
import { ModelLibrary } from "../packages/model-library/index.ts";
import type { DownloadRecord } from "../packages/contracts/index.ts";
import type { ResolvedCivitaiFile } from "../packages/model-sources/civitai/index.ts";
let root = ""; afterEach(async () => { if (root) await rm(root, { recursive: true, force: true }); });
const sha = (value: string) => createHash("sha256").update(value).digest("hex");
const source = (overrides: Partial<ResolvedCivitaiFile> = {}): ResolvedCivitaiFile => ({ resolveId: crypto.randomUUID(), providerHost: "civitai.com", modelId: 1, modelName: "Fixture", modelType: "checkpoint", versionId: 2, versionName: "v1", fileId: 3, fileName: "fixture.safetensors", sizeBytes: 7, sha256: sha("payload"), downloadUrl: "https://civitai.com/api/download/models/2", ...overrides });
async function setup(fetchMock: typeof fetch) { root = await mkdtemp(resolve(tmpdir(), "aureline-download-")); const library = new ModelLibrary(root, resolve(root, "state/index.json")); await library.load(); return { library, manager: new DownloadManager(library, fetchMock, true) }; }
async function terminal(manager: DownloadManager, start: () => Promise<DownloadRecord>): Promise<DownloadRecord> { return await new Promise(async (resolvePromise, reject) => { const timer = setTimeout(() => reject(new Error("download timeout")), 4_000); const unsubscribe = manager.subscribe(record => { if (["completed", "failed", "paused", "cancelled"].includes(record.state)) { clearTimeout(timer); unsubscribe(); resolvePromise(record); } }); await start(); }); }
function stalledResponse(init?: RequestInit): Response { const signal = init?.signal; const body = new ReadableStream<Uint8Array>({ start(controller) { controller.enqueue(new TextEncoder().encode("pay")); signal?.addEventListener("abort", () => controller.error(new DOMException("Aborted", "AbortError")), { once: true }); } }); return new Response(body, { status: 200, headers: { "content-length": "7" } }); }

describe("DownloadManager", () => {
  it("streams, reports progress, verifies SHA-256 and atomically installs", async () => { const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(new Response("payload", { status: 200, headers: { "content-length": "7" } })); const { library, manager } = await setup(fetchMock); const states: string[] = []; manager.subscribe(record => states.push(record.state)); const result = await terminal(manager, () => manager.start(source(), "checkpoints")); expect(result.state).toBe("completed"); expect(states).toEqual(expect.arrayContaining(["preflighting", "downloading", "verifying", "installing", "completed"])); expect(await readFile(resolve(root, "models/Stable-diffusion/fixture.safetensors"), "utf8")).toBe("payload"); await expect(access(resolve(root, "models/Stable-diffusion/fixture.safetensors.aureline.part"))).rejects.toThrow(); expect(library.list()).toMatchObject([{ source: "civitai", sha256: sha("payload") }]); });
  it("resumes only from a valid 206 Content-Range", async () => { const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(new Response("load", { status: 206, headers: { "content-length": "4", "content-range": "bytes 3-6/7" } })); const { manager } = await setup(fetchMock); const path = resolve(root, "models/Stable-diffusion"); await mkdir(path, { recursive: true }); await writeFile(resolve(path, "fixture.safetensors.aureline.part"), "pay"); await writeFile(resolve(path, "fixture.safetensors.aureline.part.aureline.json"), JSON.stringify({ schemaVersion: 1, provider: "civitai", providerHost: "civitai.com", modelId: 1, versionId: 2, fileId: 3, fileName: "fixture.safetensors", expectedBytes: 7, sha256: sha("payload"), receivedBytes: 3, downloadUrl: "https://civitai.com/api/download/models/2" })); const result = await terminal(manager, () => manager.start(source(), "checkpoints")); expect(result.state).toBe("completed"); expect(fetchMock.mock.calls[0]?.[1]?.headers).toMatchObject({ Range: "bytes=3-" }); });
  it("never installs a hash mismatch and allows a bounded manual retry", async () => { const fetchMock = vi.fn<typeof fetch>().mockResolvedValueOnce(new Response("retry", { status: 503 })).mockResolvedValueOnce(new Response("payload", { status: 200, headers: { "content-length": "7" } })); const { manager } = await setup(fetchMock); const result = await terminal(manager, () => manager.start(source({ sha256: "b".repeat(64) }), "checkpoints")); expect(result).toMatchObject({ state: "failed", canRetry: true, error: { code: "DOWNLOAD_HASH_MISMATCH" } }); expect(fetchMock).toHaveBeenCalledTimes(2); await expect(access(resolve(root, "models/Stable-diffusion/fixture.safetensors"))).rejects.toThrow(); });
  it("validates redirects and strips authorization on a CDN host", async () => { const fetchMock = vi.fn<typeof fetch>().mockResolvedValueOnce(new Response(null, { status: 302, headers: { location: "https://b2.civitai.com/file" } })).mockResolvedValueOnce(new Response("payload", { status: 200, headers: { "content-length": "7" } })); const { manager } = await setup(fetchMock); const result = await terminal(manager, () => manager.start(source(), "checkpoints", "test-only-key")); expect(result.state).toBe("completed"); expect(fetchMock.mock.calls[0]?.[1]?.headers).toMatchObject({ Authorization: "Bearer test-only-key" }); expect(fetchMock.mock.calls[1]?.[1]?.headers).not.toHaveProperty("Authorization"); });
  it("pauses by aborting, preserves partial data, then resumes with Range", async () => { const fetchMock = vi.fn<typeof fetch>().mockImplementationOnce(async (_input, init) => stalledResponse(init)).mockResolvedValueOnce(new Response("load", { status: 206, headers: { "content-length": "4", "content-range": "bytes 3-6/7" } })); const { manager } = await setup(fetchMock); const paused = await terminal(manager, async () => { const started = await manager.start(source(), "checkpoints"); await new Promise<void>(resolvePromise => { const unsubscribe = manager.subscribe(record => { if (record.id === started.id && record.state === "downloading" && record.receivedBytes >= 3) { unsubscribe(); manager.pause(started.id); resolvePromise(); } }); }); return started; }); expect(paused).toMatchObject({ state: "paused", receivedBytes: 3, canResume: true }); const completed = await terminal(manager, async () => manager.resume(paused.id)); expect(completed.state).toBe("completed"); expect(fetchMock.mock.calls[1]?.[1]?.headers).toMatchObject({ Range: "bytes=3-" }); });
  it("cancels and deletes partial data when requested", async () => { const fetchMock = vi.fn<typeof fetch>().mockImplementation(async (_input, init) => stalledResponse(init)); const { manager } = await setup(fetchMock); const cancelled = await terminal(manager, async () => { const started = await manager.start(source(), "checkpoints"); await new Promise<void>(resolvePromise => { const unsubscribe = manager.subscribe(record => { if (record.id === started.id && record.state === "downloading" && record.receivedBytes >= 3) { unsubscribe(); manager.cancel(started.id, true); resolvePromise(); } }); }); return started; }); expect(cancelled).toMatchObject({ state: "cancelled", canResume: false }); await expect(access(resolve(root, "models/Stable-diffusion/fixture.safetensors.aureline.part"))).rejects.toThrow(); });
  it("rejects duplicate final files before transfer", async () => { const fetchMock = vi.fn<typeof fetch>(); const { manager } = await setup(fetchMock); const path = resolve(root, "models/Stable-diffusion"); await mkdir(path, { recursive: true }); await writeFile(resolve(path, "fixture.safetensors"), "existing"); await expect(manager.start(source(), "checkpoints")).rejects.toMatchObject({ detail: { code: "DOWNLOAD_ALREADY_EXISTS" } }); expect(fetchMock).not.toHaveBeenCalled(); });
});
