import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises"; import { tmpdir } from "node:os"; import { resolve } from "node:path";
import { ModelLibrary, sanitizeModelFileName } from "../packages/model-library/index.ts";
let root = ""; afterEach(async () => { if (root) await rm(root, { recursive: true, force: true }); });
describe("ModelLibrary", () => {
  it("maps only confirmed Forge roots and fails closed for unsupported types", async () => { root = await mkdtemp(resolve(tmpdir(), "aureline-library-")); const library = new ModelLibrary(root, resolve(root, "state/index.json")); expect(library.defaultRoot("checkpoint")).toMatchObject({ id: "checkpoints", location: expect.stringContaining("models/Stable-diffusion") }); expect(library.defaultRoot("embedding").location).toContain("data / embeddings"); expect(() => library.defaultRoot("controlnet")).toThrow(/runtime-confirmed/); });
  it("scans supported files, ignores partial data, caches and flags duplicate hashes", async () => { root = await mkdtemp(resolve(tmpdir(), "aureline-library-")); const base = resolve(root, "models"); await mkdir(resolve(base, "Stable-diffusion"), { recursive: true }); await writeFile(resolve(base, "Stable-diffusion/a.safetensors"), "same"); await writeFile(resolve(base, "Stable-diffusion/b.ckpt"), "same"); await writeFile(resolve(base, "Stable-diffusion/c.safetensors.aureline.part"), "partial"); const library = new ModelLibrary(root, resolve(root, "state/index.json")); await library.load(); const models = await library.refresh(); expect(models).toHaveLength(2); expect(models.every(model => model.duplicate)).toBe(true); expect((await library.refresh()).map(model => model.sha256)).toEqual(models.map(model => model.sha256)); });
  it("sanitizes traversal and rejects unsafe extensions", () => { expect(sanitizeModelFileName("../bad:name.safetensors")).toBe("bad_name.safetensors"); expect(() => sanitizeModelFileName("model.exe")).toThrow(); });
});
