import { _electron as electron } from "playwright";
import { appendFile, cp, mkdir, rm, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { resolve } from "node:path";
import assert from "node:assert/strict";
const root=resolve(import.meta.dirname,".."),userData=resolve(root,".local/electron-smoke");await rm(userData,{recursive:true,force:true});await mkdir(resolve(userData,"engine/data/extensions/desktop-shell-smoke"),{recursive:true});await cp(resolve(root,"tests/fixtures/classic-extension"),resolve(userData,"engine/data/extensions/desktop-shell-smoke"),{recursive:true});
const electronEnvironment={...process.env,FORGE_DESKTOP_USER_DATA:userData,FORGE_DESKTOP_RUNTIME_MANIFEST:resolve(root,"runtime-manifest.example.json")};delete electronEnvironment.ELECTRON_RUN_AS_NODE;
const electronApp=await electron.launch({executablePath:resolve(root,"node_modules/electron/dist/electron.exe"),args:[root],env:electronEnvironment});
const diagnosticPath=resolve(userData,"electron-smoke.log"),record=async(value)=>await appendFile(diagnosticPath,`${String(value).replace(/Bearer\s+\S+/giu,"Bearer [REDACTED]")}\n`);
electronApp.process().stdout?.on("data",chunk=>void record(`stdout ${chunk}`));electronApp.process().stderr?.on("data",chunk=>void record(`stderr ${chunk}`));
let classicOrigin="",ownedPorts=[];
try{
  const page=await electronApp.firstWindow();page.on("console",message=>void record(`console ${message.type()} ${message.text()}`));page.on("pageerror",error=>void record(`pageerror ${error.message}`));page.on("close",()=>void record("renderer closed"));await page.waitForLoadState("domcontentloaded");await page.getByText("Forge Desktop",{exact:true}).first().waitFor();
  await page.getByRole("button",{name:"Engine",exact:true}).click();await page.getByRole("button",{name:"Start Forge"}).click();
  const outcome=await Promise.race([page.getByRole("heading",{name:"Sẵn sàng",exact:true}).waitFor({timeout:180_000}).then(()=>"ready"),page.locator(".error-box").waitFor({timeout:180_000}).then(()=>"failed")]);if(outcome==="failed")throw new Error(`Engine startup failed: ${await page.locator(".error-box").innerText()}`);
  await page.getByRole("button",{name:"Classic Forge",exact:true}).click();
  let classic;for(let attempt=0;attempt<150&&!classic;attempt+=1){classic=electronApp.context().pages().find(value=>value.url().startsWith("http://127.0.0.1"));if(!classic)await new Promise(resolvePromise=>setTimeout(resolvePromise,200))}
  assert(classic,"Classic WebContentsView page missing");const failedRequests=[],assets=[];classic.on("requestfailed",request=>failedRequests.push(`${request.url()} ${request.failure()?.errorText??"failed"}`));classic.on("response",response=>{const type=response.headers()["content-type"]??"";if(response.ok()&&(type.includes("javascript")||type.includes("css")))assets.push(response.url())});await classic.waitForLoadState("domcontentloaded");await classic.locator("gradio-app").waitFor({state:"attached",timeout:30_000});classicOrigin=new URL(classic.url()).origin;assert.equal(new URL(classic.url()).search,"");
  const rootHtml=await classic.locator("html").innerHTML();assert(rootHtml.length>500&&rootHtml.includes("gradio-app"),"Classic DOM is empty");assert(assets.some(value=>value.includes(".js")),"No representative JavaScript asset loaded");assert(assets.some(value=>value.includes(".css")),"No representative CSS asset loaded");const seriousFailures=failedRequests.filter(value=>!value.includes("ERR_ABORTED"));assert.equal(seriousFailures.length,0,`Classic assets failed: ${seriousFailures.join(", ")}`);
  const storage=await classic.evaluate(async()=>({local:Object.values(localStorage),session:Object.values(sessionStorage),indexed:(await indexedDB.databases()).map(value=>value.name),html:document.documentElement.outerHTML}));assert(!JSON.stringify(storage).includes("Bearer "),"credential leaked into browser state/source");
  const sse=await classic.evaluate(async()=>await new Promise((resolvePromise,reject)=>{const source=new EventSource("/desktop-shell-smoke/sse");source.onmessage=event=>{source.close();resolvePromise(event.data)};source.onerror=()=>reject(new Error("SSE failed"))}));assert.equal(sse,"shell-ready");
  const websocket=await classic.evaluate(async()=>await new Promise((resolvePromise,reject)=>{const socket=new WebSocket(`${location.origin.replace("http","ws")}/desktop-shell-smoke/ws`);socket.onopen=()=>socket.send("ping");socket.onmessage=event=>{resolvePromise(event.data);socket.close()};socket.onerror=()=>reject(new Error("WebSocket failed"))}));assert.equal(websocket,"forge:ping");
  await page.getByRole("button",{name:"Reload"}).click();await classic.waitForLoadState("domcontentloaded");
  const firstClassicOrigin=classicOrigin;await page.getByRole("button",{name:"Engine",exact:true}).click();const restartButton=page.getByRole("button",{name:"Restart"});await restartButton.click();for(let attempt=0;attempt<100&&!await restartButton.isDisabled();attempt+=1)await new Promise(resolvePromise=>setTimeout(resolvePromise,50));for(let attempt=0;attempt<360&&await restartButton.isDisabled();attempt+=1)await new Promise(resolvePromise=>setTimeout(resolvePromise,250));await page.getByRole("heading",{name:"Sẵn sàng",exact:true}).waitFor({timeout:180_000});await page.getByRole("button",{name:"Classic Forge",exact:true}).click();classic=undefined;for(let attempt=0;attempt<150&&!classic;attempt+=1){classic=electronApp.context().pages().find(value=>!value.isClosed()&&value.url().startsWith("http://127.0.0.1")&&new URL(value.url()).origin!==firstClassicOrigin);if(!classic)await new Promise(resolvePromise=>setTimeout(resolvePromise,200))}assert(classic,"Classic view did not reload after engine restart");await classic.locator("gradio-app").waitFor({state:"attached",timeout:30_000});classicOrigin=new URL(classic.url()).origin;assert.notEqual(classicOrigin,firstClassicOrigin,"Restart must rotate the Classic proxy origin");
  const activePorts=await new Promise((ok,fail)=>execFile("powershell.exe",["-NoProfile","-Command","$self=$PID; $owned=Get-CimInstance Win32_Process | Where-Object { $_.ProcessId -ne $self -and $_.CommandLine -like '*secure_launcher.py*' } | Select-Object -ExpandProperty ProcessId; Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | Where-Object { $_.OwningProcess -in $owned } | Select-Object -ExpandProperty LocalPort"],{windowsHide:true},(error,stdout)=>error?fail(error):ok(stdout.trim())));ownedPorts=String(activePorts).split(/\s+/).filter(Boolean).map(Number);assert(ownedPorts.length>0,"No owned Forge listener observed");
  await page.getByRole("button",{name:"Engine",exact:true}).click();await page.getByRole("button",{name:"Stop"}).click();await page.locator(".state-line h2").getByText("Đã dừng",{exact:true}).waitFor({timeout:30_000});
}finally{await electronApp.close().catch(()=>undefined)}
if(classicOrigin){await assert.rejects(fetch(classicOrigin,{signal:AbortSignal.timeout(1000)}))}
const processScan=await new Promise((ok,fail)=>execFile("powershell.exe",["-NoProfile","-Command","$self=$PID; Get-CimInstance Win32_Process | Where-Object { $_.ProcessId -ne $self -and ($_.CommandLine -like '*forge-launch-adapter*secure_launcher.py*' -or $_.ExecutablePath -like '*job-owner-helper.exe') } | Select-Object -ExpandProperty ProcessId"],{windowsHide:true},(error,stdout)=>error?fail(error):ok(stdout.trim())));assert.equal(processScan,"","Owned helper/Python process remains");
const listenerScan=await new Promise((ok,fail)=>execFile("powershell.exe",["-NoProfile","-Command",`Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | Where-Object { $_.LocalPort -in @(${ownedPorts.join(",")}) } | Select-Object -ExpandProperty LocalPort`],{windowsHide:true},(error,stdout)=>error?fail(error):ok(stdout.trim())));assert.equal(listenerScan,"","Owned listener remains");
await writeFile(resolve(userData,"smoke-result.json"),JSON.stringify({passed:true,classicOrigin,checked:["window","navigation","real-runtime","classic-dom","storage","sse","websocket","reload","restart","proxy-rotation","stop","cleanup"]},null,2));console.log("Electron smoke PASS");
