import { useEffect, useMemo, useState } from "react";
import { Activity, Box, ChevronRight, CircleGauge, Home, Maximize2, Minimize2, Moon, Play, RefreshCw, Settings, Square, StopCircle, Sun, Terminal, WandSparkles, X } from "lucide-react";
import type { DesktopSettings, EngineSnapshot, LogEvent } from "../../../../packages/contracts/index.ts";

type Page = "home" | "studio" | "classic" | "engine" | "settings";
const fallback:EngineSnapshot={state:"not_configured",phase:"Đang kết nối ứng dụng",startedAt:null,uptimeMs:0,readiness:"unknown",backendProtected:false,runtimeId:null,error:null};
const labels:Record<EngineSnapshot["state"],string>={not_configured:"Chưa cấu hình",stopped:"Đã dừng",starting:"Đang khởi động",ready:"Sẵn sàng",stopping:"Đang dừng",failed:"Cần chú ý"};
const nav:Array<{id:Page;label:string;icon:typeof Home}>=[{id:"home",label:"Home",icon:Home},{id:"studio",label:"Studio",icon:WandSparkles},{id:"classic",label:"Classic Forge",icon:Box},{id:"engine",label:"Engine",icon:CircleGauge},{id:"settings",label:"Settings",icon:Settings}];
function duration(ms:number):string{const seconds=Math.floor(ms/1000);if(seconds<60)return `${seconds}s`;const minutes=Math.floor(seconds/60);return `${minutes}m ${seconds%60}s`}

export function App(){
  const [page,setPage]=useState<Page>("home"),[engine,setEngine]=useState(fallback),[logs,setLogs]=useState<LogEvent[]>([]),[settings,setSettings]=useState<DesktopSettings|null>(null),[busy,setBusy]=useState(false);
  useEffect(()=>{void window.aureline.engine.getState().then(setEngine);void window.aureline.logs.getRecent().then(setLogs);void window.aureline.settings.get().then(setSettings);const offState=window.aureline.engine.subscribe(setEngine),offLog=window.aureline.logs.subscribe(event=>setLogs(value=>[...value.slice(-99),event]));return()=>{offState();offLog()}},[]);
  useEffect(()=>{if(page!=="classic")void window.aureline.classic.hide();else if(engine.state==="ready")void window.aureline.classic.show().catch(()=>setPage("engine"));},[page,engine.state]);
  useEffect(()=>{if(!settings)return;document.documentElement.dataset.theme=settings.theme;if(settings.theme==="system")document.documentElement.dataset.systemDark=String(matchMedia("(prefers-color-scheme: dark)").matches)},[settings]);
  const action=async(kind:"start"|"stop"|"restart")=>{setBusy(true);try{setEngine(await window.aureline.engine[kind]())}finally{setBusy(false)}};
  const select=(next:Page)=>{setPage(next)};
  return <div className="app">
    <header className="titlebar"><div className="brand-mark"><Activity size={16}/></div><span>Aureline</span><div className="drag"/><div className="window-actions"><button aria-label="Thu nhỏ" onClick={()=>void window.aureline.app.window("minimize")}><Minimize2/></button><button aria-label="Phóng to" onClick={()=>void window.aureline.app.window("toggle-maximize")}><Maximize2/></button><button className="close" aria-label="Đóng" onClick={()=>void window.aureline.app.window("close")}><X/></button></div></header>
    <aside className="sidebar"><div className="product"><div className="logo">A</div><div><strong>Aureline</strong><span>Creative studio</span></div></div><nav>{nav.map(item=><button key={item.id} className={page===item.id?"active":""} onClick={()=>select(item.id)}><item.icon/><span>{item.label}</span>{item.id==="studio"&&<small>Sắp có</small>}</button>)}</nav><div className="sidebar-status"><Status state={engine.state}/><div><strong>{labels[engine.state]}</strong><span>{engine.phase}</span></div></div></aside>
    <main className="content">{page==="home"&&<HomePage engine={engine} logs={logs} busy={busy} action={action} openClassic={()=>select("classic")}/>} {page==="studio"&&<StudioPage/>} {page==="classic"&&<ClassicPage engine={engine} busy={busy} action={action}/>} {page==="engine"&&<EnginePage engine={engine} logs={logs} busy={busy} action={action}/>} {page==="settings"&&settings&&<SettingsPage value={settings} onChange={async patch=>{const next=await window.aureline.settings.update(patch);setSettings(next)}}/>}</main>
  </div>;
}
function Status({state}:{state:EngineSnapshot["state"]}){return <span className={`status-dot ${state}`} aria-hidden="true"/>}
function PageTitle({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:React.ReactNode}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{actions&&<div className="page-actions">{actions}</div>}</div>}
function EngineActions({engine,busy,action}:{engine:EngineSnapshot;busy:boolean;action:(kind:"start"|"stop"|"restart")=>Promise<void>}){return <>{engine.state!=="ready"&&engine.state!=="starting"?<button className="primary" disabled={busy||engine.state==="not_configured"} onClick={()=>void action("start")}><Play/>Start Forge</button>:<button disabled={busy} onClick={()=>void action("stop")}><StopCircle/>Stop</button>}<button disabled={busy||engine.state!=="ready"} onClick={()=>void action("restart")}><RefreshCw/>Restart</button></>}
function HomePage({engine,logs,busy,action,openClassic}:{engine:EngineSnapshot;logs:LogEvent[];busy:boolean;action:(k:"start"|"stop"|"restart")=>Promise<void>;openClassic:()=>void}){return <><PageTitle eyebrow="Workspace" title="Aureline" description="Studio sáng tạo AI local-first dành cho quy trình hình ảnh trên Windows." actions={<EngineActions engine={engine} busy={busy} action={action}/>}/><section className="hero"><div><span className="hero-kicker"><Status state={engine.state}/>{labels[engine.state]}</span><h2>{engine.state==="ready"?"Engine đã sẵn sàng.":engine.state==="not_configured"?"Kết nối runtime để bắt đầu.":"Forge đang ở trạng thái kiểm soát."}</h2><p>{engine.phase}</p><button className="text-button" disabled={engine.state!=="ready"} onClick={openClassic}>Mở Classic Forge <ChevronRight/></button></div><div className="engine-orbit"><Activity/><span>{engine.backendProtected?"Protected":"Offline"}</span></div></section><section className="metric-grid"><Metric icon={Terminal} label="Runtime" value={engine.runtimeId??"Chưa kết nối"} note="Python + Forge manifest"/><Metric icon={CircleGauge} label="Readiness" value={engine.readiness==="ready"?"Đã xác minh":"Chưa sẵn sàng"} note="Identity + capability"/><Metric icon={Activity} label="GPU" value="Chưa kết nối" note="Telemetry ở milestone sau"/></section><ActivityList logs={logs.slice(-4).reverse()}/></>}
function Metric({icon:Icon,label,value,note}:{icon:typeof Home;label:string;value:string;note:string}){return <article className="metric"><div className="icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function ActivityList({logs}:{logs:LogEvent[]}){return <section className="panel"><div className="panel-title"><div><span className="eyebrow">Recent activity</span><h3>Engine timeline</h3></div></div>{logs.length===0?<div className="empty"><Activity/><p>Hoạt động engine sẽ xuất hiện tại đây.</p></div>:<div className="activity-list">{logs.map((log,index)=><div key={`${log.timestamp}-${index}`}><span className={`level ${log.level}`}/><time>{new Date(log.timestamp).toLocaleTimeString()}</time><p>{log.message}</p></div>)}</div>}</section>}
function StudioPage(){return <><PageTitle eyebrow="Studio" title="Không gian sáng tạo đang được chuẩn bị" description="Milestone này tập trung vào nền tảng engine và Classic Forge. Generation workspace sẽ đến ở bước tiếp theo."/><div className="coming"><WandSparkles/><span>Studio foundation</span><h2>Prompt workspace, model discovery và txt2img contract</h2><p>Chưa có dữ liệu giả hoặc generation action trong bản này.</p></div></>}
function ClassicPage({engine,busy,action}:{engine:EngineSnapshot;busy:boolean;action:(k:"start"|"stop"|"restart")=>Promise<void>}){return <><div className="classic-toolbar"><div><span className="eyebrow">Compatibility mode</span><h1>Classic Forge</h1><p>{engine.state==="ready"?"Giao diện Forge gốc đang chạy trong isolated WebContentsView.":engine.phase}</p></div><div className="page-actions"><button disabled={engine.state!=="ready"} onClick={()=>void window.aureline.classic.reload()}><RefreshCw/>Reload</button><button disabled={busy} onClick={()=>void action(engine.state==="ready"?"restart":"start")}><Play/>{engine.state==="ready"?"Restart engine":"Start engine"}</button></div></div>{engine.state!=="ready"&&<div className="classic-state"><Box/><h2>{engine.state==="starting"?"Forge đang khởi động":"Classic Forge chưa sẵn sàng"}</h2><p>{engine.phase}</p></div>}</>}
function EnginePage({engine,logs,busy,action}:{engine:EngineSnapshot;logs:LogEvent[];busy:boolean;action:(k:"start"|"stop"|"restart")=>Promise<void>}){return <><PageTitle eyebrow="Runtime control" title="Engine" description="Theo dõi lifecycle, protected readiness và diagnostics đã redaction." actions={<EngineActions engine={engine} busy={busy} action={action}/>}/><section className="engine-grid"><div className="panel engine-card"><span className="eyebrow">Current state</span><div className="state-line"><Status state={engine.state}/><h2>{labels[engine.state]}</h2></div><p>{engine.phase}</p>{engine.error&&<div className="error-box"><strong>{engine.error.message}</strong><span>{engine.error.code}</span>{engine.error.details&&<details><summary>Technical details</summary><pre>{engine.error.details}</pre></details>}</div>}</div><div className="panel facts"><Fact label="Uptime" value={engine.startedAt?duration(engine.uptimeMs):"—"}/><Fact label="Readiness" value={engine.readiness}/><Fact label="Backend guard" value={engine.backendProtected?"Active":"Inactive"}/><Fact label="Runtime" value={engine.runtimeId??"Not configured"}/></div></section><section className="panel logs"><div className="panel-title"><div><span className="eyebrow">Bounded diagnostics</span><h3>Live logs</h3></div><Terminal/></div><div className="log-scroll">{logs.length===0?<p className="muted">Chưa có log.</p>:logs.slice(-80).map((log,index)=><div key={`${log.timestamp}-${index}`}><time>{new Date(log.timestamp).toLocaleTimeString()}</time><span className={log.level}>{log.level}</span><p>{log.message}</p></div>)}</div></section></>}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function SettingsPage({value,onChange}:{value:DesktopSettings;onChange:(patch:Partial<Omit<DesktopSettings,"schemaVersion">>)=>Promise<void>}){return <><PageTitle eyebrow="Preferences" title="Settings" description="Thiết lập shell được lưu atomic trong user data; runtime path chỉ đọc."/><section className="settings-list"><Setting title="Theme" description="Theo hệ thống hoặc chọn giao diện cố định."><div className="segmented">{(["system","light","dark"] as const).map(item=><button className={value.theme===item?"active":""} onClick={()=>void onChange({theme:item})} key={item}>{item==="light"?<Sun/>:item==="dark"?<Moon/>:<Settings/>}{item}</button>)}</div></Setting><Setting title="Launch Forge when app starts" description="Khởi động engine sau khi shell sẵn sàng."><input type="checkbox" checked={value.launchOnStart} onChange={event=>void onChange({launchOnStart:event.target.checked})}/></Setting><Setting title="Close behavior" description="Milestone 1 luôn cleanup engine trước khi thoát."><select value={value.closeBehavior} onChange={event=>void onChange({closeBehavior:event.target.value as DesktopSettings["closeBehavior"]})}><option value="stop-and-quit">Stop engine and quit</option><option value="quit">Quit</option></select></Setting><Setting title="Log level" description="Diagnostics được giới hạn và redaction."><select value={value.logLevel} onChange={event=>void onChange({logLevel:event.target.value as DesktopSettings["logLevel"]})}><option value="info">Info</option><option value="debug">Debug</option></select></Setting><Setting title="Advanced" description="Runtime management và release channels sẽ có ở milestone sau."><span className="badge">Sắp có</span></Setting></section></>}
function Setting({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="setting"><div><strong>{title}</strong><p>{description}</p></div>{children}</div>}
